/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sk.stu.fiit.controller.CategoryController;
import sk.stu.fiit.controller.RoomController;
import sk.stu.fiit.data.Data;
import sk.stu.fiit.exceptions.BlankFields;
import sk.stu.fiit.model.Category;
import sk.stu.fiit.model.Customer;
import sk.stu.fiit.model.Room;

/**
 *
 * @author jarni
 */
public class AddRoom extends javax.swing.JFrame {

    /**
     * Creates new form AddRoom
     */
    
    MainWindow main;
    boolean edit;
    List<BufferedImage> images = null;
    Room room;
    
    
    public AddRoom(MainWindow main) {
        this.main = main;
        initComponents();
        
        
        List<String> names = new ArrayList<String>();
        for (Category cat: Data.getAllCategories()){
            names.add(cat.getName());
        }
        
        String[] array = names.toArray(new String[0]);
        
        cmbCategory.setModel(new DefaultComboBoxModel(array));
    }
    
    void initEdit(Room room) {
        edit = true;
        lblHeading.setText("Editovanie izby");
        txfId.setText(room.getId());
        txaDesc.setText(room.getNote());
        System.out.println(room.getNote());
        cmbCategory.setSelectedItem(room.getCategory().getName());
        this.images = room.getImages();
        this.room = room;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDesc = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        btnAddImages = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblHeading.setText("Pridanie izby");
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(txfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Poznámka");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txaDesc.setColumns(20);
        txaDesc.setRows(5);
        jScrollPane1.setViewportView(txaDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, 110));

        btnSave.setText("Uložiť");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSaveMouseReleased(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 100, 40));

        btnCancel.setText("Zrušiť");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Kategória");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, -1));

        btnAddImages.setText("Pridať obrázky");
        btnAddImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddImagesMouseReleased(evt);
            }
        });
        getContentPane().add(btnAddImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 220, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        dispose();
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseReleased
        RoomController con = new RoomController();
        
        int cat = cmbCategory.getSelectedIndex();
        
        if (cat < 0){
            JOptionPane.showMessageDialog(rootPane, "Vyberte kategóriu izby.", "Nevybraná kategória", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                if (edit)
                    con.editRoom(room, txfId.getText(), cat, txaDesc.getText(), images);
                else
                    con.addRoom(txfId.getText(), cat, txaDesc.getText(), images);
                
                main.initTableRooms();
                dispose();
            } catch (BlankFields ex) {
                JOptionPane.showMessageDialog(rootPane, "Vyplňte všetky povinné polia.", "Nevyplnené údaje", JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSaveMouseReleased

    private void btnAddImagesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddImagesMouseReleased
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG, JPG, PNG, BMP, GIF", "jpeg", "jpg", "png", "bmp", "gif");
        fileChooser.setFileFilter(filter);
        int value = fileChooser.showOpenDialog(this);
        if(value == JFileChooser.APPROVE_OPTION) {
            try {
                if (this.images == null)
                    this.images = new ArrayList<BufferedImage>();
                
                this.images.add(ImageIO.read(fileChooser.getSelectedFile()));
                
            } catch (IOException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnAddImagesMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddImages;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JTextArea txaDesc;
    private javax.swing.JTextField txfId;
    // End of variables declaration//GEN-END:variables

    
}
