/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sk.stu.fiit.data.Data;
import sk.stu.fiit.model.Customer;
import sk.stu.fiit.model.Reservation;
import sk.stu.fiit.model.Service;

/**
 *
 * @author jarni
 */
public class CustomerProfile extends javax.swing.JFrame {

    /**
     * Creates new form CustomerProfile
     */
    Customer cus;
    List<Reservation> reservs = null;
    
    public CustomerProfile(Customer cus) {
        this.cus = cus;
        initComponents();
        
        lblHeading.setText(cus.getFirstName() + " " +  cus.getLastName());
        
        for (Reservation res: Data.getAllReservations()){                
            if (res.getCustomer().equals(cus)){
                reservs.add(res);
            }        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        lblHeading = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnShowServices = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        List<String> columns = new ArrayList<String>();
        List<String[]> values = new ArrayList<String[]>();

        for (Reservation res: Data.getAllReservations()){
            if (res.getCustomer().equals(cus)){
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

                String fromS = sdf.format(res.getFrom());
                String toS = sdf.format(res.getTo());
                String payS = sdf.format(res.getPayment().getDate());

                values.add(new String[] {fromS, toS, res.getRoom().getId() + " - " + res.getRoom().getCategory().getName(), payS, String.format("%.2f EUR", res.getPriceAll())});

            }
        }

        columns.add("Začiatok");
        columns.add("Koniec");
        columns.add("Izba");
        columns.add("Dátum a spôsob platby");
        columns.add("Celková cena (aj služby)");

        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
        tblReservations.setModel(tableModel);
        jScrollPane1.setViewportView(tblReservations);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 100));

        tblServices.setModel(new DefaultTableModel());
        jScrollPane2.setViewportView(tblServices);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 420, 100));

        lblHeading.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblHeading.setText("Meno Priezvisko");
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Rezervácie a ubytovania");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOkMouseReleased(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 50, 30));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Využité služby");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        btnShowServices.setText("Pozrieť služby k vybranej rezervácii");
        btnShowServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnShowServicesMouseReleased(evt);
            }
        });
        getContentPane().add(btnShowServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseReleased
        dispose();
    }//GEN-LAST:event_btnOkMouseReleased

    private void btnShowServicesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowServicesMouseReleased
        int res = tblReservations.getSelectedRow();
        
        if (res < 0){
            JOptionPane.showMessageDialog(rootPane, "Vyberte rezerváciu", "Nevybraná rezervácia", JOptionPane.ERROR_MESSAGE);
        }
        
        List<String> columns = new ArrayList<String>();
        List<String[]> values = new ArrayList<String[]>();

        for (Service ser: reservs.get(res).getServices()){                
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

            String dateS = sdf.format(ser.getDate());

            values.add(new String[] {ser.getName(), ser.getDesc(), String.format("%.2f EUR", ser.getPrice()), dateS});
      
        }

        columns.add("Názov");
        columns.add("Opis");
        columns.add("Cena");
        columns.add("Dátum");

        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
        tblServices.setModel(tableModel);

    }//GEN-LAST:event_btnShowServicesMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnShowServices;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTable tblServices;
    // End of variables declaration//GEN-END:variables
}
