/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author jarni
 */
public class SetTime extends javax.swing.JFrame {

    /**
     * Creates new form SetTime
     */
    
    private MainWindow main;
    public SetTime(MainWindow main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ftxfDate = new javax.swing.JFormattedTextField();
        ftxfTime = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSet = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ftxfDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(ftxfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 130, -1));

        ftxfTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        getContentPane().add(ftxfTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Čas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Dátum");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setText("tvar: dd. mm. rrrr");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, 30));

        jLabel4.setText("tvar: h:mm:ss");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 30));

        btnSet.setText("Nastaviť dátum a čas");
        btnSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSetMouseReleased(evt);
            }
        });
        getContentPane().add(btnSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 40));

        btnCancel.setText("Zrušiť");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        dispose();
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnSetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetMouseReleased
        String date = ftxfDate.getText();
        String time = ftxfTime.getText();
        
        System.out.println(date);
        String[] parsedDate = date.split(" ");
        String[] parsedTime = time.split(":");
        
        System.out.println(parsedDate.length);
        for (int i = 0; i < parsedDate.length; i++) {
            String string = parsedDate[i];
            System.out.println(string);
        }
        
        int day = Integer.parseInt(parsedDate[0].replace(".", ""));
        int month = Integer.parseInt(parsedDate[1].replace(".", ""));
        int year = Integer.parseInt(parsedDate[2].replace(".", ""));
        
        int hour = Integer.parseInt(parsedTime[0]);
        int minute = Integer.parseInt(parsedTime[1]);
        int second = Integer.parseInt(parsedTime[2]);
        
        Calendar mojCalendar = new GregorianCalendar();
        int dayReal = mojCalendar.get(Calendar.DATE);
        int monthReal = mojCalendar.get(Calendar.MONTH) + 1;
        int yearReal = mojCalendar.get(Calendar.YEAR);

        int hourReal = mojCalendar.get(Calendar.HOUR_OF_DAY);
        int minuteReal = mojCalendar.get(Calendar.MINUTE);
        int secondReal = mojCalendar.get(Calendar.SECOND);
        
        MainWindow.setExit(true);
        main.dateAndTime(day - dayReal, month - monthReal, year - yearReal, hour - hourReal, minute - minuteReal, second - secondReal);
        MainWindow.setExit(false);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSet;
    private javax.swing.JFormattedTextField ftxfDate;
    private javax.swing.JFormattedTextField ftxfTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
