/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import sk.stu.fiit.model.Room;

/**
 *
 * @author jarni
 */
public class ShowGallery extends javax.swing.JFrame {

    /**
     * Creates new form ShowGallery
     */
    public ShowGallery(Room room) {
        initComponents();
        
        for (BufferedImage image : room.getImages()) {
            JLabel lbl = new JLabel();
            
            lbl.setIcon(new ImageIcon(image));
            pnlFotos.add(lbl);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFotos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFotos.setLayout(new javax.swing.BoxLayout(pnlFotos, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlFotos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlFotos;
    // End of variables declaration//GEN-END:variables
}
